# -*- coding: utf-8 -*-
"""automate_ArifPohan.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R53JfTPVP7FJOYnRXDBvPocGFlCpV4L
"""

import argparse
import pandas as pd
from sklearn.preprocessing import StandardScaler


def preprocess_data(input_path, output_path):
    df = pd.read_csv(input_path)

    # Outlier handling
    outlier_cols = ["trestbps", "chol", "thalach"]
    for col in outlier_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        df[col] = df[col].clip(Q1 - 1.5*IQR, Q3 + 1.5*IQR)

    # Encoding
    categorical_cols = ["cp", "restecg", "slope", "thal"]
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

    # Scaling
    X = df.drop("target", axis=1)
    y = df["target"]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    df_preprocessed = pd.DataFrame(X_scaled, columns=X.columns)
    df_preprocessed["target"] = y.values

    df_preprocessed.to_csv(output_path, index=False)
    return df_preprocessed


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Automated preprocessing")
    parser.add_argument("--input_path", type=str, required=True)
    parser.add_argument("--output_path", type=str, required=True)

    args = parser.parse_args()

    preprocess_data(
        input_path=args.input_path,
        output_path=args.output_path
    )